version: "3.7"

services:
  saltcorn-app:
    image: saltcorn/saltcorn:latest
    container_name: saltcorn
    depends_on:
      - saltcorn-db
    command: "serve"
    restart: always
    networks:
      - saltcorn
      - proxy
    ports: #not needed if using traefik
      - "3000:3000"
    environment:
      - SALTCORN_SESSION_SECRET=${SALTCORN_SECRET}
      - SALTCORN_SECRET=${SALTCORN_SECRET}
      - SALTCORN_FILE_STORE=${SALTCORN_FILE_STORE}
      - PGHOST=saltcorn-db
      - PGUSER=${PGUSER}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
    labels: # If using traefik to reverse proxy into saltcorn
      - traefik.http.routers.saltcornsecure.rule=Host(`saltcorn.${DOMAIN}`)
      - traefik.http.routers.saltcornsecure.entrypoints=websecure
      - traefik.http.routers.saltcorn.rule=Host(`saltcorn.docker.localhost`)
      - traefik.http.routers.saltcorn.entrypoints=web
      - traefik.enable=true
    
  saltcorn-db:
    image: postgres:13-alpine
    restart: always
    networks:
      - saltcorn
    volumes:
      - db_data:/var/lib/postgresql/data #save the db to a mount point if you wish, otherwise will use docker container management
      - ./docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/init.sql # This is the init script for the database
    environment:
      - POSTGRES_USER=${PGUSER} # initdb.sql script will only work for user "postgres"
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}

networks:
  saltcorn:
    name: saltcorn-net
  proxy:
    external: true

volumes:
  db_data: